services:
  postgres:
    image: postgres
    container_name: python_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - python_postgres_data:/var/lib/postgresql

  redis:
    image: redis
    container_name: python_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - python_redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: python_mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    volumes:
      - python_mailpit_data:/data
    restart: unless-stopped

volumes:
  python_postgres_data:
  python_redis_data:
  python_mailpit_data:
